name: "ci"
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GODOT_VERSION: 4.2.2
  PROJECT_DIR: catalyst
  LIB_DIR: catalyst-lib

jobs:
  export-linux:
    name: Export Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "${{ env.LIB_DIR }} -> target"
      - run: |
          cargo build
          cargo test --all-features
          cargo build --release
        working-directory: ${{ env.LIB_DIR }}
      - uses: chickensoft-games/setup-godot@v2
        with:
          version: ${{ env.GODOT_VERSION }}
          include-templates: true
      - run: |
          mkdir -p build/linux/catalyst
          godot --headless --path ${{ env.PROJECT_DIR }} --export-release linux ../build/linux/catalyst/catalyst.x86_64
          echo "output_directory=build/linux" >> $GITHUB_OUTPUT
        id: export
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: ${{ steps.export.outputs.output_directory }}
